[workspace]
members = ["crates/inphzugzwang-core", "crates/inphzugzwang-eval", "crates/inphzugzwang-nnue", "crates/inphzugzwang-syzygy", "crates/inphzugzwang-search", "crates/inphish", "tools/tune"]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
strip = true
