#!/usr/bin/env python3
# Writes tests/nnue/reference.txt: positions with the raw NNUE value Stockfish 13 gives them.
# Needs a local Stockfish 13 build with one extra UCI command, `rawnnue`, that prints
# Eval::NNUE::evaluate(pos): the network output divided by FV_SCALE, for the side to move. Usage: tools/nnue_reference.py PATH_TO_STOCKFISH_13 > tests/nnue/reference.txt
import random, subprocess, sys

engine = subprocess.Popen([sys.argv[1]], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, bufsize=1)

def send(line):
    engine.stdin.write(line + '\n')

def read_until(prefix):
    while True:
        line = engine.stdout.readline()
        if not line:
            sys.exit('stockfish exited')
        if line.startswith(prefix):
            return line.strip()

def legal_moves(fen):
    send(f'position fen {fen}')
    send('go perft 1')
    moves = []
    while True:
        line = engine.stdout.readline().strip()
        if line.startswith('Nodes searched'):
            return moves
        if ':' in line:
            moves.append(line.split(':')[0])

def after(fen, move):
    send(f'position fen {fen} moves {move}')
    send('d')
    return read_until('Fen:')[5:]

def raw(fen):
    send(f'position fen {fen}')
    send('rawnnue')
    while True:
        line = engine.stdout.readline().strip()
        if line.lstrip('-').isdigit():
            return int(line)

def normalise(text):
    fields = text.split()
    return ' '.join(fields[:4] + (fields[4:6] if len(fields) >= 6 else ['0', '1']))

seeds = []
for path, column in (('tests/perft/standard.txt', 3), ('tests/perft/chess960.txt', 3)):
    seeds += [line.split('|')[column] for line in open(path) if line.strip()]
seeds += [line.split('|')[3] for line in open('tests/perft/chess960_starts.txt')][::96]
seeds += [' '.join(line.split()[:4]) for line in open('tests/openings/balanced.epd') if line.strip()]
seeds = list(dict.fromkeys(normalise(fen) for fen in seeds))

random.seed(20260925)
positions = list(seeds)
start = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'
for game in range(170):
    fen = random.choice(seeds + [start] * 20)
    for ply in range(random.randint(20, 160)):
        moves = legal_moves(fen)
        if not moves:
            break
        fen = after(fen, random.choice(moves))
        if ply % 7 == 3:
            positions.append(fen)
positions = list(dict.fromkeys(positions))

send('uci')
read_until('uciok')
print('# fen|stockfish 13 raw nnue value, side to move; net nn-62ef826d1a6d, generated by tools/nnue_reference.py')
for fen in positions:
    if legal_moves(fen):
        print(f'{fen}|{raw(fen)}')
send('quit')
