#!/usr/bin/env python3
# Writes tests/syzygy/reference.txt: random legal positions with at most five pieces and the
# WDL and DTZ values Stockfish 13 probes for them. Needs a local Stockfish 13 build with one
# extra UCI command, `tbprobe`, printing probe_wdl, its state, probe_dtz and its state, plus
# an inphish binary to reject illegal positions.
# Usage: tools/syzygy_reference.py STOCKFISH_13 INPHISH SYZYGY_DIR > tests/syzygy/reference.txt
import random, subprocess, sys

stockfish, inphish, tables = sys.argv[1:4]
engine = subprocess.Popen([stockfish], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, bufsize=1)

def send(line):
    engine.stdin.write(line + '\n')

def probe(fen):
    send(f'position fen {fen}')
    send('tbprobe')
    while True:
        fields = engine.stdout.readline().split()
        if len(fields) == 4 and all(field.lstrip('-').isdigit() for field in fields):
            return fields

def legal(fen):
    return subprocess.run([inphish, 'perft', '1', '--fen', fen], capture_output=True).returncode == 0

def square(file, rank):
    return rank * 8 + file

def fen_of(board, side, ep):
    rows = []
    for rank in range(7, -1, -1):
        row, empty = '', 0
        for file in range(8):
            piece = board.get(square(file, rank))
            if piece:
                row += (str(empty) if empty else '') + piece
                empty = 0
            else:
                empty += 1
        rows.append(row + (str(empty) if empty else ''))
    return f"{'/'.join(rows)} {side} - {ep} 0 1"

def en_passant_position(rng):
    # A pawn of the side to move beside an enemy pawn that has just advanced two squares.
    board = {}
    side = rng.choice('wb')
    file = rng.randrange(8)
    beside = rng.choice([f for f in (file - 1, file + 1) if 0 <= f < 8])
    rank, mover, victim = (4, 'P', 'p') if side == 'w' else (3, 'p', 'P')
    board[square(file, rank)] = victim
    board[square(beside, rank)] = mover
    free = [s for s in range(64) if s not in board and s not in (square(file, rank + (1 if side == 'w' else -1)), square(file, rank + (2 if side == 'w' else -2)))]
    kings = rng.sample(free, 2)
    while abs(kings[0] % 8 - kings[1] % 8) <= 1 and abs(kings[0] // 8 - kings[1] // 8) <= 1:
        kings = rng.sample(free, 2)
    board[kings[0]], board[kings[1]] = 'K', 'k'
    if rng.random() < 0.6:
        piece = rng.choice('QRBNPqrbnp')
        choices = [s for s in free if s not in board and (piece not in 'Pp' or 8 <= s < 56)]
        board[rng.choice(choices)] = piece
    ep = 'abcdefgh'[file] + ('6' if side == 'w' else '3')
    return fen_of(board, side, ep)

def random_position(rng):
    if rng.random() < 0.1:
        return en_passant_position(rng)
    board = {}
    kings = rng.sample(range(64), 2)
    while abs(kings[0] % 8 - kings[1] % 8) <= 1 and abs(kings[0] // 8 - kings[1] // 8) <= 1:
        kings = rng.sample(range(64), 2)
    board[kings[0]], board[kings[1]] = 'K', 'k'
    for _ in range(rng.choice([1, 2, 2, 3, 3, 3])):
        piece = rng.choice('QRRBBNNPPPP')
        piece = piece if rng.random() < 0.5 else piece.lower()
        choices = [s for s in range(64) if s not in board and (piece not in 'Pp' or 8 <= s < 56)]
        board[rng.choice(choices)] = piece
    side = rng.choice('wb')
    ep = '-'
    # Offer an en passant square when the side to move has a pawn beside an enemy pawn that
    # could just have advanced two squares.
    for target, piece in list(board.items()):
        rank, file = target // 8, target % 8
        if side == 'w' and piece == 'p' and rank == 4:
            behind, start = square(file, 5), square(file, 6)
            beside = [board.get(square(f, 4)) for f in (file - 1, file + 1) if 0 <= f < 8]
            if 'P' in beside and behind not in board and start not in board and rng.random() < 0.7:
                ep = 'abcdefgh'[file] + '6'
        if side == 'b' and piece == 'P' and rank == 3:
            behind, start = square(file, 2), square(file, 1)
            beside = [board.get(square(f, 3)) for f in (file - 1, file + 1) if 0 <= f < 8]
            if 'p' in beside and behind not in board and start not in board and rng.random() < 0.7:
                ep = 'abcdefgh'[file] + '3'
    return fen_of(board, side, ep)

send('uci')
send(f'setoption name SyzygyPath value {tables}')
send('isready')
while engine.stdout.readline().strip() != 'readyok':
    pass

rng = random.Random(20260925)
seen = set()
print('# fen|wdl|wdl state|dtz|dtz state from Stockfish 13 probe_wdl and probe_dtz, generated by tools/syzygy_reference.py')
while len(seen) < 4000:
    fen = random_position(rng)
    if fen in seen or not legal(fen):
        continue
    seen.add(fen)
    print(f"{fen}|{'|'.join(probe(fen))}")
send('quit')
