[package]
name = "inphish"
version = "3.1.1"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
inphzugzwang-core = { path = "../inphzugzwang-core" }
inphzugzwang-eval = { path = "../inphzugzwang-eval" }
inphzugzwang-nnue = { path = "../inphzugzwang-nnue" }
inphzugzwang-syzygy = { path = "../inphzugzwang-syzygy" }
inphzugzwang-search = { path = "../inphzugzwang-search" }
